spring:
  datasource:
    druid:
      db1:
        url: jdbc:mysql://172.16.79.42:3306/sign_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
        username: root
        password: Sign@2020
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        url: jdbc:mysql://172.16.36.18:3306/xedk_one?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true&allowMultiQueries=true
        username: xedk
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
